### ISSUE TITLE
same type of relation not allowed from one node to multiple nodes

### ISSUE THREAD

**Issue by alperyilmaz** [tombenke/proper#1]
Here's the yaml data I would like to convert into graph (only single node is shown):
```yaml
ArticleA:
    _description: article title for A
    _relations:
        cites:
           _target: ArticleB
        cites:
           _target: ArticleC
```

But in the graph, node A is only linked to node C, and I'm guessing the problem is that relation type for both node B and C are `cites`. Isn't it allowed to have same type of relation multiple times originating from same node? If I change one of the `cites` into `cites2` node A can link to both node B and C successfully.

I'm not good at js code but app.js line no 75 says that:
```
for( var relation in relations ) {
```
And thus I'm guessing the code iterates over all relations and so I don't know what the problem might be in this case.

**Comment by tombenke** [comment]
In principle a yaml file is a so-called fat-free JSON file. JSON stands for JavaScript Object Notation. It means that yaml (as well as JSON) files represent JavaScript objects. The hierarchy described here is a nested objects, where the relation types are properties of their parent object. And you can use the same property name only once for a specific object. In case you use the same name several times, probably the last one will be the winner, which overwrites the previous ones.

**Comment by alperyilmaz** [comment]
I see, I thought `_relations` would accept an array of objects, but it looks like it accepts objects only (instead of an array) so a key can be used only once.. 
Thanks for your answer..

**Comment by alperyilmaz** [comment]
I tried to convert `_relations` into array of objects and still didn't work :( 
I wish had known more js, it looks like an easy fix within a for each loop..

```yaml
ArticleA:
    _description: article title for A
    _relations:
         - cites:
              _target: ArticleB
         - cites: 
              _target: ArticleC
```
